# ================================================================
#  Project: Health Facility Accessibility Service Gaps Analysis
# ================================================================

country_code: "KEN"

crs: "EPSG:4326"
output_crs: "EPSG:3857"
crs_utm: "EPSG:32737"

output_dir: "outputs"

project:
  name: "Health Facility Accessibility Service Gaps Analysis"
  country: "Kenya"
  region: "Kisii County"
  crs: "EPSG:4326"         # CRS for input data
  output_crs: "EPSG:3857"  # CRS for analysis/visualization    # Example UTM CRS for Kenya

# ----------------------------------------------------------------
#  DATA SOURCES (All local)
# ----------------------------------------------------------------
data_dir: "data"

population:
  raster: "data/population/population.tif"
  zonal_output: "data/population/population_by_admin.geojson"
  field: "population"

facilities:
  csv: "data/facilities/facilities.csv"
  geojson: "data/facilities/facilities.geojson"
  name_field: "Facility_N"
  type_field: "Type"

roads:
  path: "data/roads/road_network.geojson"
  speed_field: "speed_kph"

admin_boundaries:
  folder: "data/Administrative_boundaries"   # folder containing all shapefiles
  crs_field: "EPSG:32737"                    # UTM CRS for processing
  id_field: "ward_id"                        # optional
  name_field: "ward_name"                    # optional

# ----------------------------------------------------------------
#  DOWNLOAD OPTIONS (disabled for fully offline)
# ----------------------------------------------------------------
download:
  enabled: false

# ----------------------------------------------------------------
#  TRAVEL & ACCESSIBILITY PARAMETERS
# ----------------------------------------------------------------
travel:
  mode: "driving"         
  max_travel_time: 60     
  speed_defaults:         
    driving: 50
    walking: 5
    cycling: 15
  travel_cost_metric: "time"
  routing_engine: "osmnx"

# ----------------------------------------------------------------
#  SERVICE GAP THRESHOLDS
# ----------------------------------------------------------------
accessibility:
  service_radius_km: 10
  catchment_thresholds: [15, 30, 60]  
  gap_definition: "population_outside_30min"
  min_population_gap: 1000

# ----------------------------------------------------------------
#  ANALYSIS OPTIONS
# ----------------------------------------------------------------
analysis:
  aggregate_by: "ward"
  weighting: "population"
  output_tables: true
  output_maps: true
  save_intermediate: false

# ----------------------------------------------------------------
#  VISUALIZATION
# ----------------------------------------------------------------
visualization:
  generate_facility_map: true
  generate_accessibility_map: true
  # center: [-0.6799, 34.7519]
  map_title: "Health Service Accessibility"
  zoom_level: 10
  colormap: "YlOrRd"
  legend_labels: ["< 15 min", "15–30 min", "30–60 min", "> 60 min"]
  show_facilities: true
  basemap: "OpenStreetMap"
  output_format: "png"

# ----------------------------------------------------------------
#  OUTPUT PATHS
# ----------------------------------------------------------------
output:
  directory: "outputs"
  accessibility_map: "outputs/accessibility_map.png"
  gap_table: "outputs/service_gaps.csv"
  reports: "outputs/reports/"

# ----------------------------------------------------------------
#  LOGGING
# ----------------------------------------------------------------
logging:
  level: "INFO"
  log_file: "logs/accessibility.log"
  overwrite: true
